missionChip color get expertMissionChips 
s55 
missionChip 
getDefaultConfiguration getDefaultScreenDevice getLocalGraphicsEnvironment GraphicsEnvironment gc GraphicsConfiguration 
gc color expertMission loadMissionChip 
expertMission 
