DisbandUnitAction freeColClient FreeColClient 
freeColClient getKeyStroke KeyStroke 
BUTTON_IMAGE UNIT_BUTTON_DISBAND ImageLibrary getUnitButtonImageIcon getImageLibrary freeColClient putValue 
BUTTON_ROLLOVER_IMAGE getUnitButtonImageIcon getImageLibrary freeColClient putValue 
UNIT_BUTTON_DISBAND ImageLibrary 
