BLOB Types registerColumnType 
CLOB Types registerColumnType 
USE_STREAMS_FOR_BINARY Environment setProperty getDefaultProperties 
STATEMENT_BATCH_SIZE Environment DEFAULT_BATCH_SIZE setProperty getDefaultProperties 
StandardSQLFunction registerFunction 
StandardSQLFunction registerFunction 
StandardSQLFunction registerFunction 
SMALLINT Types registerColumnType 
STRING StandardBasicTypes StandardSQLFunction registerFunction 
TINYINT Types registerColumnType 
StandardSQLFunction registerFunction 
INTEGER Types registerColumnType 
STRING StandardBasicTypes StandardSQLFunction registerFunction 
CHAR Types registerColumnType 
TIMESTAMP StandardBasicTypes StandardSQLFunction registerFunction 
VARCHAR Types registerColumnType 
TIMESTAMP StandardBasicTypes NoArgSQLFunction registerFunction 
FLOAT Types registerColumnType 
TIMESTAMP StandardBasicTypes NoArgSQLFunction registerFunction 
DOUBLE Types registerColumnType 
StandardSQLFunction registerFunction 
DATE Types registerColumnType 
TIME Types registerColumnType 
TIMESTAMP Types registerColumnType 
TimesTenDialect 
BIT Types registerColumnType 
BIGINT Types registerColumnType 
VARBINARY Types registerColumnType 
NUMERIC Types registerColumnType 
